/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingEventRouteImport } from './routes/upcomingEvent'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PrincipalRouteImport } from './routes/principal'
import { Route as NewsFeedRouteImport } from './routes/newsFeed'
import { Route as ManagementRouteImport } from './routes/management'
import { Route as HolidaysRouteImport } from './routes/holidays'
import { Route as GoogleStreetViewRouteImport } from './routes/googleStreetView'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as EventDetailsRouteImport } from './routes/eventDetails'
import { Route as DirectorRouteImport } from './routes/director'
import { Route as ContactUsRouteImport } from './routes/contactUs'
import { Route as CoCurricularActivitiesRouteImport } from './routes/co-curricular-activities'
import { Route as BeyondAcademicRouteImport } from './routes/beyondAcademic'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const UpcomingEventRoute = UpcomingEventRouteImport.update({
  id: '/upcomingEvent',
  path: '/upcomingEvent',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalRoute = PrincipalRouteImport.update({
  id: '/principal',
  path: '/principal',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsFeedRoute = NewsFeedRouteImport.update({
  id: '/newsFeed',
  path: '/newsFeed',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysRoute = HolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleStreetViewRoute = GoogleStreetViewRouteImport.update({
  id: '/googleStreetView',
  path: '/googleStreetView',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const EventDetailsRoute = EventDetailsRouteImport.update({
  id: '/eventDetails',
  path: '/eventDetails',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorRoute = DirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contactUs',
  path: '/contactUs',
  getParentRoute: () => rootRouteImport,
} as any)
const CoCurricularActivitiesRoute = CoCurricularActivitiesRouteImport.update({
  id: '/co-curricular-activities',
  path: '/co-curricular-activities',
  getParentRoute: () => rootRouteImport,
} as any)
const BeyondAcademicRoute = BeyondAcademicRouteImport.update({
  id: '/beyondAcademic',
  path: '/beyondAcademic',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admission': typeof AdmissionRoute
  '/beyondAcademic': typeof BeyondAcademicRoute
  '/co-curricular-activities': typeof CoCurricularActivitiesRoute
  '/contactUs': typeof ContactUsRoute
  '/director': typeof DirectorRoute
  '/eventDetails': typeof EventDetailsRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/googleStreetView': typeof GoogleStreetViewRoute
  '/holidays': typeof HolidaysRoute
  '/management': typeof ManagementRoute
  '/newsFeed': typeof NewsFeedRoute
  '/principal': typeof PrincipalRoute
  '/results': typeof ResultsRoute
  '/upcomingEvent': typeof UpcomingEventRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admission': typeof AdmissionRoute
  '/beyondAcademic': typeof BeyondAcademicRoute
  '/co-curricular-activities': typeof CoCurricularActivitiesRoute
  '/contactUs': typeof ContactUsRoute
  '/director': typeof DirectorRoute
  '/eventDetails': typeof EventDetailsRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/googleStreetView': typeof GoogleStreetViewRoute
  '/holidays': typeof HolidaysRoute
  '/management': typeof ManagementRoute
  '/newsFeed': typeof NewsFeedRoute
  '/principal': typeof PrincipalRoute
  '/results': typeof ResultsRoute
  '/upcomingEvent': typeof UpcomingEventRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admission': typeof AdmissionRoute
  '/beyondAcademic': typeof BeyondAcademicRoute
  '/co-curricular-activities': typeof CoCurricularActivitiesRoute
  '/contactUs': typeof ContactUsRoute
  '/director': typeof DirectorRoute
  '/eventDetails': typeof EventDetailsRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/googleStreetView': typeof GoogleStreetViewRoute
  '/holidays': typeof HolidaysRoute
  '/management': typeof ManagementRoute
  '/newsFeed': typeof NewsFeedRoute
  '/principal': typeof PrincipalRoute
  '/results': typeof ResultsRoute
  '/upcomingEvent': typeof UpcomingEventRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/admission'
    | '/beyondAcademic'
    | '/co-curricular-activities'
    | '/contactUs'
    | '/director'
    | '/eventDetails'
    | '/facilities'
    | '/gallery'
    | '/googleStreetView'
    | '/holidays'
    | '/management'
    | '/newsFeed'
    | '/principal'
    | '/results'
    | '/upcomingEvent'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/admission'
    | '/beyondAcademic'
    | '/co-curricular-activities'
    | '/contactUs'
    | '/director'
    | '/eventDetails'
    | '/facilities'
    | '/gallery'
    | '/googleStreetView'
    | '/holidays'
    | '/management'
    | '/newsFeed'
    | '/principal'
    | '/results'
    | '/upcomingEvent'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/admission'
    | '/beyondAcademic'
    | '/co-curricular-activities'
    | '/contactUs'
    | '/director'
    | '/eventDetails'
    | '/facilities'
    | '/gallery'
    | '/googleStreetView'
    | '/holidays'
    | '/management'
    | '/newsFeed'
    | '/principal'
    | '/results'
    | '/upcomingEvent'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  AdmissionRoute: typeof AdmissionRoute
  BeyondAcademicRoute: typeof BeyondAcademicRoute
  CoCurricularActivitiesRoute: typeof CoCurricularActivitiesRoute
  ContactUsRoute: typeof ContactUsRoute
  DirectorRoute: typeof DirectorRoute
  EventDetailsRoute: typeof EventDetailsRoute
  FacilitiesRoute: typeof FacilitiesRoute
  GalleryRoute: typeof GalleryRoute
  GoogleStreetViewRoute: typeof GoogleStreetViewRoute
  HolidaysRoute: typeof HolidaysRoute
  ManagementRoute: typeof ManagementRoute
  NewsFeedRoute: typeof NewsFeedRoute
  PrincipalRoute: typeof PrincipalRoute
  ResultsRoute: typeof ResultsRoute
  UpcomingEventRoute: typeof UpcomingEventRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcomingEvent': {
      id: '/upcomingEvent'
      path: '/upcomingEvent'
      fullPath: '/upcomingEvent'
      preLoaderRoute: typeof UpcomingEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal': {
      id: '/principal'
      path: '/principal'
      fullPath: '/principal'
      preLoaderRoute: typeof PrincipalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsFeed': {
      id: '/newsFeed'
      path: '/newsFeed'
      fullPath: '/newsFeed'
      preLoaderRoute: typeof NewsFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays': {
      id: '/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof HolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/googleStreetView': {
      id: '/googleStreetView'
      path: '/googleStreetView'
      fullPath: '/googleStreetView'
      preLoaderRoute: typeof GoogleStreetViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventDetails': {
      id: '/eventDetails'
      path: '/eventDetails'
      fullPath: '/eventDetails'
      preLoaderRoute: typeof EventDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/director': {
      id: '/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof DirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactUs': {
      id: '/contactUs'
      path: '/contactUs'
      fullPath: '/contactUs'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/co-curricular-activities': {
      id: '/co-curricular-activities'
      path: '/co-curricular-activities'
      fullPath: '/co-curricular-activities'
      preLoaderRoute: typeof CoCurricularActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beyondAcademic': {
      id: '/beyondAcademic'
      path: '/beyondAcademic'
      fullPath: '/beyondAcademic'
      preLoaderRoute: typeof BeyondAcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  AdmissionRoute: AdmissionRoute,
  BeyondAcademicRoute: BeyondAcademicRoute,
  CoCurricularActivitiesRoute: CoCurricularActivitiesRoute,
  ContactUsRoute: ContactUsRoute,
  DirectorRoute: DirectorRoute,
  EventDetailsRoute: EventDetailsRoute,
  FacilitiesRoute: FacilitiesRoute,
  GalleryRoute: GalleryRoute,
  GoogleStreetViewRoute: GoogleStreetViewRoute,
  HolidaysRoute: HolidaysRoute,
  ManagementRoute: ManagementRoute,
  NewsFeedRoute: NewsFeedRoute,
  PrincipalRoute: PrincipalRoute,
  ResultsRoute: ResultsRoute,
  UpcomingEventRoute: UpcomingEventRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
